// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQGleWVKICh-Rn32SiIJef4VpsEd3QPHc',
    appId: '1:821726272760:web:2b55ae8efa97e290616f0d',
    messagingSenderId: '821726272760',
    projectId: 'flutter-grocery-app-df567',
    authDomain: 'flutter-grocery-app-df567.firebaseapp.com',
    storageBucket: 'flutter-grocery-app-df567.appspot.com',
    measurementId: 'G-KCYNGX7KDX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmmOtIGrqlQHV1NFbso-_jHUYXxoL574s',
    appId: '1:821726272760:android:2cf23ea74be2eacf616f0d',
    messagingSenderId: '821726272760',
    projectId: 'flutter-grocery-app-df567',
    storageBucket: 'flutter-grocery-app-df567.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpWsyZkSsP2UF16e1UiNdf0xQEee8wd9I',
    appId: '1:821726272760:ios:1a95687f809f2b5a616f0d',
    messagingSenderId: '821726272760',
    projectId: 'flutter-grocery-app-df567',
    storageBucket: 'flutter-grocery-app-df567.appspot.com',
    iosBundleId: 'com.haluuvananh.shoppingAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpWsyZkSsP2UF16e1UiNdf0xQEee8wd9I',
    appId: '1:821726272760:ios:8e5c3e00e7d39de9616f0d',
    messagingSenderId: '821726272760',
    projectId: 'flutter-grocery-app-df567',
    storageBucket: 'flutter-grocery-app-df567.appspot.com',
    iosBundleId: 'com.example.shoppingAppFlutter.RunnerTests',
  );
}
